### ISSUE TITLE
Defmacro/quote?

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme_system#5]
Just curious, what are the defmacro/quote things here:

https://github.com/exponentially/extreme_system/blob/master/lib/system/facade.ex

(I'm no familiar with Elixir this much). What are the advantages of using them vs regular (non-macro) code?

Thanks.

**Comment by mjaric** [comment]
Whole elixir is built using macros. defmodule, def, defp, defstruct ... are elixir built in macros. Think of them as compiler directives that generates elixir code then compiler picks that generated code and compiles it into beam binary. This is simplest explanation, but there is a lot more thing that are there. Like AST tables that are actually what is under the hood. quote do <block> end is way to tell elixir compile what code is "template" for your macro, that body is translated into AST table. Here is how it looks

```elixir
iex(2)> quote do
...(2)> Enum.reduce(1..5, 0, fn i, acc -> acc + i end)
...(2)> end
{{:., [], [{:__aliases__, [alias: false], [:Enum]}, :reduce]}, [],
 [
   {:.., [context: Elixir, import: Kernel], [1, 5]},
   0,
   {:fn, [],
    [
      {:->, [],
       [
         [
           {:i, [context: Elixir, import: IEx.Helpers], Elixir},
           {:acc, [], Elixir}
         ],
         {:+, [context: Elixir, import: Kernel],
          [
            {:acc, [], Elixir},
            {:i, [context: Elixir, import: IEx.Helpers], Elixir}
          ]}
       ]}
    ]}
 ]}
iex(3)>
```

If you closely look at generated table, you will see that each tuple in that table represents:
1. Function
2. Context and module that holds that function
3. parameters that should be passed to fuction

For example
`{:..,          [context: Elixir, import: Kernel],             [1, 5]  }`
that can be read as:
`{ <range function>,  <in Elixir context where module is Kernel>,   <parameters for function> }`
and translates back into `1..5` when final code need to be finally compiled.

then, elixir compiler can read this AST table and generate code in plase where you are calling your macro. If you are using macro indside quote do ... end, that macro will be expanded in AST table too, you can try that if you want.

So if you need to write DSL (domain specific language) then you probably want to use macros. For instance Ecto Query is built that way. When you write ecto query, for instance this:

`Repo.one(conn, from(p in People, where: p.id == ^id))`

Actually it is compiled into:

`Repo.one(conn, ["SELECT p1.id, p1.name, p1.email FROM people as p1 WHERE p1.id = $1", [id]])`

here you can see what that `id` is expected to be in scope of macro call, that is what is called *macro Hygiene* in documentation sometimes you want it to depend on outer variables in scope where it is called, since id must be defined by caller code.

Now consider this:

```elixir
defmacro some_macto() do
   <script>
   quote do
      <body>
   end
end
```

`defmacro` will `unquote` what `quote do .... end` "quotes"/makes AST where `<script>` is pre processor that will be run during compile time. Usually there you can prepare what ever you need in terms of data for your quote part. Any variable defined in `<script>` then need to be `unquote`-ed in quote `<body>`. 

So in extreme_system, the file you referred, is just template code that you would usually write if there were no macros to save you such headache. Think of it as routing DSL.

**Comment by burmajam** [comment]
Regarding Facades. They are `public API` for your application or bounding context. They are like Phoenix router. GenServer.call is sent to Facade, it spawns task for this request (so it can accept others while first one is being processed) and responds back. It also has optional caching:

```elixir
  use     Extreme.System.Facade, default_cache: 1_000
```

This means that each request will be hashed and cached for 1 sec. So if you receive 2 identical requests in less then a second, second one will receive response that was cached.

**Comment by drozzy** [comment]
Got it. Just read Elixir guide on macros too. 

Seems like this is very advanced. I still find this very complex and hard to understand (I personally prefer the non-Dry version :-) but that's just me).

Anyways, thanks for the explanation.

**Comment by drozzy** [comment]
Why not write a function instead, like this (again, I'm still learning):

```
Facade.route(:change_business_address, UserMessageHandler)
```

With implementation like this (pseudocode):
```
Facade

   routes = []

  def route(cmd, handler) do
     routes.append({cmd, handler})
  end

def handle_call(cmd, from, state) do
   if(cmd in handlers) do
     handler = handlers[cmd]
     Logger.metadata metadata
     Logger.info fn -> "Routing #{inspect cmd} to UserMessageHandler#change_business_address" end
     req_id = hash(:change_business_address, params)
     execute(state, req_id, from, fn ->
     Logger.metadata metadata
     call(handler, cmd, [params])
   end)
   {:noreply, state}
end
